### ISSUE TITLE
update license

### ISSUE THREAD

**Issue by diveshuttam** [pro-panda/bob-the-bot#4]
[bob-the-bot/src/menu_update.py](https://github.com/pro-panda/bob-the-bot/blob/master/src/menu_update.py) is quite similar to [MessMenuBot/extractmenu/menuextract.py](https://github.com/diveshuttam/MessMenuBot/blob/master/extractmenu/menuextract.py)

It would be great if you could comply with the [MessMenuBot/LICENCE](https://github.com/diveshuttam/MessMenuBot/blob/master/LICENSE)

Close this issue if it is a coincidence.

**Comment by diveshuttam** [comment]
MIT doesn't require individual file copyrights if its same throughout the project. 
Can you please put the copy of LICENCE or the copyright notice to the bottom/top of the file as you please.

**Comment by pro-panda** [comment]
Please make a PR of the copyright snippet appended
